[package]
name = "town-links"
version = "0.1.0"
edition = "2021"

[dependencies]
imgui = "0.8"
imgui-wgpu = "0.20"
imgui-winit-support = { version = "0.8", features = ["winit-26"], default-features = false }
winit = "0.26"
wgpu = "0.13"
env_logger = "0.9"
log = "0.4"
