[package]
name = "town-links"
version = "0.1.0"
edition = "2021"

[dependencies]
imgui = "0.8.2"
imgui-glium-renderer = "0.8.2"
glium = { version = "0.30.2", default-features = true }
imgui-winit-support = "0.8.2"
